"""empty message

Revision ID: 07435892867a
Revises: b5cb44f908ca
Create Date: 2024-01-03 23:02:46.520061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07435892867a'
down_revision = 'b5cb44f908ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=150),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
