"""empty message

Revision ID: 2337793d9019
Revises: 60ae2b6fcd56
Create Date: 2024-01-01 18:24:25.530581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2337793d9019'
down_revision = '60ae2b6fcd56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_pass')
    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pass', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pass', ['id_pass'], ['id_pass'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id_pass')

    op.create_table('_alembic_tmp_pass',
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=150), nullable=True),
    sa.Column('expiration_date', sa.DATETIME(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('id_pass', sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
