"""empty message

Revision ID: 758d5266d489
Revises: c67b62e8cace
Create Date: 2024-01-04 01:40:11.121173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758d5266d489'
down_revision = 'c67b62e8cace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_book')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=150),
               existing_nullable=True)

    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date', sa.DATE(), nullable=True))

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=150),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_book',
    sa.Column('author', sa.VARCHAR(length=150), nullable=True),
    sa.Column('name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('location', sa.VARCHAR(length=150), nullable=True),
    sa.Column('status', sa.VARCHAR(length=150), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
