"""empty message

Revision ID: 94b62bb8da72
Revises: e5a1b5c2263f
Create Date: 2024-01-01 14:59:18.893253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b62bb8da72'
down_revision = 'e5a1b5c2263f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pass', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('id_pass')

    # ### end Alembic commands ###
