"""empty message

Revision ID: f4f5618c6524
Revises: 758d5266d489
Create Date: 2024-01-04 22:35:18.908199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f5618c6524'
down_revision = '758d5266d489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_book', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('return_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rents', schema=None) as batch_op:
        batch_op.drop_column('return_date')
        batch_op.drop_column('date')
        batch_op.drop_column('id_user')
        batch_op.drop_column('id_book')

    # ### end Alembic commands ###
