"""empty message

Revision ID: fb2043016cd4
Revises: 1762fa4545bb
Create Date: 2024-01-01 14:57:48.782867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2043016cd4'
down_revision = '1762fa4545bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('donations', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['id_pass'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('donations')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
